controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    arm_controller: # Adjust controller name
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
    state_publish_rate: 20.0
    action_monitor_rate: 10.0
    allow_partial_joints_goal: false
